In [57]:
#sutun nasil pratik olarak secilir 
#loc methodu
#iloc methodu 
#coklu secme
#coklu filtreleme
import pandas as pd

In [58]:
film = pd.read_csv("http://bit.ly/imdbratings")
film

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [59]:
film.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [60]:
#selection , farki sekillerde yapilabilir / koslei parantez 
#1den fazla sutun gostermek istersek , 2 tane koseli parantez icine yazilir 
film[["title","genre","duration"]].head()

                      title   genre  duration
0  The Shawshank Redemption   Crime       142
1             The Godfather   Crime       175
2    The Godfather: Part II   Crime       200
3           The Dark Knight  Action       152
4              Pulp Fiction   Crime       154

In [61]:
#loc methodu (ilk deger sutun, 2. deger satiei gosterecek ) 
#0 yazip bosluk birakirsak 1 numarali filmi gosterecek 
#1 den fazla secmek icin yine 2 tane koseli parantez 
film.loc[[0,5,10],]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
10,8.8,The Lord of the Rings: The Fellowship of the Ring,PG-13,Adventure,178,"[u'Elijah Wood', u'Ian McKellen', u'Orlando Bl..."

In [62]:
#ilk 5 filmin title ve genresi
film.loc[0:5,["title","genre"]]

                      title   genre
0  The Shawshank Redemption   Crime
1             The Godfather   Crime
2    The Godfather: Part II   Crime
3           The Dark Knight  Action
4              Pulp Fiction   Crime
5              12 Angry Men   Drama

In [63]:
#title den genreye kadar tun sutunlari aliyor , koseli parantez kalkti 
film.loc[0:5,"star_rating":"duration"]

   star_rating                     title content_rating   genre  duration
0          9.3  The Shawshank Redemption              R   Crime       142
1          9.2             The Godfather              R   Crime       175
2          9.1    The Godfather: Part II              R   Crime       200
3          9.0           The Dark Knight          PG-13  Action       152
4          8.9              Pulp Fiction              R   Crime       154
5          8.9              12 Angry Men      NOT RATED   Drama        96

In [64]:
#ilk satiri bos birakacak da bu islem yapilabilir 
#loc her zaman sutunlari gosteriyor 
film.loc[:,"title":"genre":]

                                               title content_rating      genre
0                           The Shawshank Redemption              R      Crime
1                                      The Godfather              R      Crime
2                             The Godfather: Part II              R      Crime
3                                    The Dark Knight          PG-13     Action
4                                       Pulp Fiction              R      Crime
..                                               ...            ...        ...
974                                          Tootsie             PG     Comedy
975                      Back to the Future Part III             PG  Adventure
976  Master and Commander: The Far Side of the World          PG-13     Action
977                                      Poltergeist             PG     Horror
978                                      Wall Street              R      Crime

[979 rows x 3 columns]

In [65]:
#loc ile suzme islemi
#sadece Crime turundeki filmleri goster
#sona viegul koymak onemli
film.loc[film.genre=="Crime",]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
21,8.7,City of God,R,Crime,130,"[u'Alexandre Rodrigues', u'Matheus Nachtergael..."
...,...,...,...,...,...,...
927,7.5,Brick,R,Crime,110,"[u'Joseph Gordon-Levitt', u'Lukas Haas', u'Emi..."
931,7.4,Mean Streets,R,Crime,112,"[u'Robert De Niro', u'Harvey Keitel', u'David ..."
950,7.4,Bound,R,Crime,108,"[u'Jennifer Tilly', u'Gina Gershon', u'Joe Pan..."
969,7.4,Law Abiding Citizen,R,Crime,109,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']"
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [66]:
#sadece title sutunu yazdirmak, 
film.loc[film.genre=="Crime",["title","duration"]]

                        title  duration
0    The Shawshank Redemption       142
1               The Godfather       175
2      The Godfather: Part II       200
4                Pulp Fiction       154
21                City of God       130
..                        ...       ...
927                     Brick       110
931              Mean Streets       112
950                     Bound       108
969       Law Abiding Citizen       109
978               Wall Street       126

[124 rows x 2 columns]

In [67]:
#iloc methodu , loc tan farki, satir ve sutunlarin indexlerini gosterir
#bu veride 0. index degeri "star_rating" o yuzden sistem onu ekrana getirdi 
film.iloc[:,2].head()

0        R
1        R
2        R
3    PG-13
4        R
Name: content_rating, dtype: object

In [68]:
#0dan 5e kadar olan satirlarin 0dan 3e kadae olan sutunlarinin indexleri yazildi 
film.iloc[0:5,0:3]

   star_rating                     title content_rating
0          9.3  The Shawshank Redemption              R
1          9.2             The Godfather              R
2          9.1    The Godfather: Part II              R
3          9.0           The Dark Knight          PG-13
4          8.9              Pulp Fiction              R

In [69]:
#0dan 5e kadar olan satirlarin tum suutnlari 
film.iloc[0:5, :]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [71]:
#coklu filtreleme
#hem 200dk dan uzun, hem Crime olan filmler
film [(film.duration>=200)&(film.genre=="Crime")]

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."

In [77]:
#200dk dan uzun veya crime 
film [(film.duration>=200)|(film.genre=="Crime")]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
...,...,...,...,...,...,...
927,7.5,Brick,R,Crime,110,"[u'Joseph Gordon-Levitt', u'Lukas Haas', u'Emi..."
931,7.4,Mean Streets,R,Crime,112,"[u'Robert De Niro', u'Harvey Keitel', u'David ..."
950,7.4,Bound,R,Crime,108,"[u'Jennifer Tilly', u'Gina Gershon', u'Joe Pan..."
969,7.4,Law Abiding Citizen,R,Crime,109,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']"
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [79]:
#birden fazla ayni sutundan secme yapmak icin "isin" methodu kullaniyoruz
film[film.genre.isin(["Action","Crime","Adventure"])]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
967,7.4,The Rock,R,Action,136,"[u'Sean Connery', u'Nicolas Cage', u'Ed Harris']"
969,7.4,Law Abiding Citizen,R,Crime,109,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']"
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."